import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {navigation as Navigator} from "@/components/navigation";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Elician | Quest Holder',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
         <Navigator/>
         {children}
      </body>
    </html>
  )
}
